# Generated by Django 4.0.10 on 2023-03-02 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this name belongs to the category of the book', max_length=225, verbose_name='Category_name')),
                ('description', models.CharField(blank=True, help_text='this is the description of the category of book', max_length=500, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'All Book Category',
                'verbose_name_plural': 'All Books Category',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='this is the unique identifier of an object', primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('title', models.CharField(blank=True, help_text='the address one is basically the defualt address of the property', max_length=250, null=True, verbose_name='Title')),
                ('book_description', models.TextField(blank=True, help_text='the description of what the book is all about', null=True, verbose_name='Book Description')),
                ('price', models.CharField(blank=True, help_text='this is the amount the book is sold', max_length=50, null=True, verbose_name='Book Price')),
                ('pages', models.IntegerField(blank=True, help_text='this is the number of pages of the book', max_length=10, null=True, verbose_name='Numbers of book pages')),
                ('book_image', models.ImageField(blank=True, help_text='Book images for the current  book, which should be in PNG, JPEG, or JPG format', null=True, upload_to='photos/books_image', verbose_name='Book Image')),
                ('book_file', models.FileField(blank=True, help_text='Book file for the current book, which should be in PDF format', null=True, upload_to='PDF/Books_file', verbose_name='Book File')),
                ('website', models.URLField(blank=True, help_text='Portfolio website for the authur of the book', max_length=250, null=True, verbose_name='Portfolio Website')),
                ('status', models.CharField(choices=[('Unpublished', 'Unpublished'), ('Published', 'Published')], default='Unpublished', help_text='Status of the book', max_length=30, verbose_name='Status')),
                ('books', models.ForeignKey(help_text=' this profile belongs to the author  who owns this book ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Books_author', to=settings.AUTH_USER_MODEL, verbose_name='Author of the book')),
                ('category', models.ForeignKey(help_text=' this category name of the book', on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name=' Book Category')),
            ],
            options={
                'verbose_name': 'All Landlord Properties',
                'verbose_name_plural': 'All Landlord Properties',
                'ordering': ('-created_date',),
            },
        ),
    ]
