# Generated by Django 4.0.10 on 2023-03-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('-created_date',), 'verbose_name': 'All Authors Book', 'verbose_name_plural': 'All Authors Book'},
        ),
    ]
