# Generated by Django 4.0.10 on 2023-03-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_category_description_category_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='books',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_option',
        ),
    ]
