# Generated by Django 4.0.10 on 2023-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_books_books_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_option',
            field=models.CharField(help_text='this name belongs to the category of the book', max_length=225, verbose_name='Category_option'),
        ),
    ]
