# Generated by Django 4.0.10 on 2023-03-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_category_category_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_option',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AddField(
            model_name='books',
            name='book_category',
            field=models.ForeignKey(help_text='Category type refers to the type of the book based on the category', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='books',
            name='date_time_added',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time', null=True, verbose_name='Date & Time Added'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(blank=True, help_text='this is the title of the book given  by the author', max_length=250, null=True, verbose_name='Title'),
        ),
    ]
